CREATE TABLE CONFIGS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  KEY VARCHAR2(255) NOT NULL,
  VALUE CLOB NOT NULL,
  DESCRIPTION VARCHAR2(500)
);
/

CREATE TABLE PROXY_KEYS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  KEY VARCHAR2(255) NOT NULL,
  STATUS VARCHAR2(100)
);
/

INSERT INTO PROXY_KEYS (ID, KEY, STATUS) 
VALUES (1, '91MAktXjGz6SkXFazTflLjdAxnYbknlh', 'A');
/
