create table "Investors"
(
    ID               NUMBER(19) generated by default on null as identity
        constraint "PK_Investors"
            primary key,
    NO               VARCHAR2(150)               not null,
    FULLNAME         VARCHAR2(250)               not null,
    EMAIL            VARCHAR2(250),
    PHONE            VARCHAR2(250)               not null,
    CREATEDDATE      TIMESTAMP(7) WITH TIME ZONE not null,
    LASTMODIFIEDDATE TIMESTAMP(7) WITH TIME ZONE
)
/
