CREATE OR REPLACE VIEW V_PROPOSED_BRANCH AS
SELECT
    r.ID,
    r.ENTITY_ID,
    r.STATUS,
    r.ACTION,
    r.REQUESTED_BY       AS CREATED_BY,
    r.REQUESTED_DATE AS CREATED_DATE,
    r.APPROVED_BY     AS CHECKER_ID,
    r.APPROVE_DATE   AS APPROVE_DATE,
    r.APPROVED_BY     AS UPDATED_BY,
    r.APPROVE_DATE   AS UPDATED_DATE,
    JSON_VALUE(r.REQUESTED_DATA, '$.Code'        RETURNING VARCHAR2(50)   NULL ON EMPTY NULL ON ERROR)  AS CODE,
    JSON_VALUE(r.REQUESTED_DATA, '$.Name'        RETURNING VARCHAR2(256)  NULL ON EMPTY NULL ON ERROR)  AS NAME,
    JSON_VALUE(r.REQUESTED_DATA, '$.Description' RETURNING VARCHAR2(500)  NULL ON EMPTY NULL ON ERROR)  AS DESCRIPTION,
    CASE
        WHEN LOWER(JSON_VALUE(r.REQUESTED_DATA, '$.IsActive' RETURNING VARCHAR2(5) NULL ON EMPTY NULL ON ERROR)) IN ('true','1','y') THEN 'Y'
        WHEN LOWER(JSON_VALUE(r.REQUESTED_DATA, '$.IsActive' RETURNING VARCHAR2(5) NULL ON EMPTY NULL ON ERROR)) IN ('false','0','n') THEN 'N'
        ELSE NULL
    END AS IS_ACTIVE
FROM BRANCH_REQUESTS r;