CREATE OR REPLACE VIEW V_PROPOSED_USER AS
SELECT
    r.ID,
    r.ENTITY_ID,
    r.STATUS,
    r.ACTION,
    r.MAKER_ID       AS CREATED_BY,
    r.REQUESTED_DATE AS CREATED_DATE,
    r.CHECKER_ID     AS CHECKER_ID,
    r.APPROVE_DATE   AS APPROVE_DATE,
    r.CHECKER_ID     AS UPDATED_BY,
    r.APPROVE_DATE   AS UPDATED_DATE,
    JSON_VALUE(r.REQUESTED_DATA, '$.UserName'           RETURNING VARCHAR2(256)  NULL ON EMPTY NULL ON ERROR) AS USER_NAME,
    JSON_VALUE(r.REQUESTED_DATA, '$.NormalizedUserName' RETURNING VARCHAR2(256)  NULL ON EMPTY NULL ON ERROR) AS NORMALIZED_USER_NAME,
    JSON_VALUE(r.REQUESTED_DATA, '$.Email'              RETURNING VARCHAR2(256)  NULL ON EMPTY NULL ON ERROR) AS EMAIL,
    JSON_VALUE(r.REQUESTED_DATA, '$.NormalizedEmail'    RETURNING VARCHAR2(256)  NULL ON EMPTY NULL ON ERROR) AS NORMALIZED_EMAIL,
    JSON_VALUE(r.REQUESTED_DATA, '$.FullName'           RETURNING NVARCHAR2(200) NULL ON EMPTY NULL ON ERROR) AS FULL_NAME,
    JSON_VALUE(r.REQUESTED_DATA, '$.PhoneNumber'        RETURNING VARCHAR2(20)   NULL ON EMPTY NULL ON ERROR) AS PHONE_NUMBER,
    CASE
        WHEN LOWER(JSON_VALUE(r.REQUESTED_DATA, '$.IsActive' RETURNING VARCHAR2(5) NULL ON EMPTY NULL ON ERROR)) IN ('true','1','y') THEN 'Y'
        WHEN LOWER(JSON_VALUE(r.REQUESTED_DATA, '$.IsActive' RETURNING VARCHAR2(5) NULL ON EMPTY NULL ON ERROR)) IN ('false','0','n') THEN 'N'
        ELSE NULL
    END AS IS_ACTIVE,
    JSON_VALUE(r.REQUESTED_DATA, '$.BranchId'           RETURNING NUMBER         NULL ON EMPTY NULL ON ERROR) AS BRANCH_ID
FROM USER_REQUESTS r
/



