CREATE OR REPLACE VIEW V_ROLE_REQUEST AS
SELECT
    r.ID,
    r.ENTITY_ID,
    r.STATUS,
    r.ACTION,
    r.MAKER_ID       AS CREATED_BY,
    r.REQUESTED_DATE AS CREATED_DATE,
    r.CHECKER_ID     AS CHECKER_ID,
    r.APPROVE_DATE   AS APPROVE_DATE,
    r.CHECKER_ID     AS UPDATED_BY,
    r.APPROVE_DATE   AS UPDATED_DATE,
    json_value(CAST(r.REQUESTED_DATA AS VARCHAR2(4000)), '$.Code')        AS CODE,
    json_value(CAST(r.REQUESTED_DATA AS VARCHAR2(4000)), '$.Name')        AS NAME,
    json_value(CAST(r.REQUESTED_DATA AS VARCHAR2(4000)), '$.Description') AS DESCRIPTION,
    json_value(CAST(r.REQUESTED_DATA AS VARCHAR2(4000)), '$.IsActive')    AS IS_ACTIVE
FROM ROLE_REQUESTS r
/
