CREATE OR REPLACE VIEW V_ROLE_REQUESTS_PENDING AS
SELECT
    r.ID,
    r.ENTITY_ID,
    r.STATUS,
    r.ACTION,
    r.MAKER_ID       AS CREATED_BY,
    r.REQUESTED_DATE AS CREATED_DATE,
    r.CHECKER_ID     AS APPROVE_BY,
    r.APPROVE_DATE   AS APPROVE_DATE,
    jt.ROLE_CODE,
    jt.ROLE_NAME,
    jt.DESCRIPTION
FROM USER_REQUESTS r
CROSS APPLY JSON_TABLE(
    r.REQUESTED_DATA, '$'
    COLUMNS (
        ROLE_CODE       VARCHAR2(50)    PATH '$.Code',
        ROLE_NAME       VARCHAR2(256)   PATH '$.Name',
        DESCRIPTION     VARCHAR2(1000)  PATH '$.Description'
    )
) jt;
/
