CREATE OR REPLACE VIEW V_USER_REQUESTS AS
SELECT
    CAST(r.ID AS NUMBER(19))            AS REQUEST_ID,
    CAST(r.ENTITY_ID AS NUMBER(19))     AS ENTITY_ID,
    CAST(r.STATUS AS VARCHAR2(10))      AS STATUS,
    CAST(r.ACTION AS VARCHAR2(20))      AS ACTION,
    CAST(r.MAKER_ID AS VARCHAR2(256))   AS REQUESTED_BY,
    CAST(r.REQUESTED_DATE AS TIMESTAMP(6)) AS REQUESTED_DATE,
    CAST(jt.USER_NAME AS VARCHAR2(128)) AS USER_NAME,
    CAST(jt.FULL_NAME AS VARCHAR2(256)) AS FULL_NAME,
    CAST(jt.EMAIL AS VARCHAR2(1000))    AS EMAIL
FROM USER_REQUESTS r
CROSS APPLY JSON_TABLE(
    r.REQUESTED_DATA, '$'
    COLUMNS (
        USER_NAME       VARCHAR2(128)   PATH '$.UserName',
        FULL_NAME       VARCHAR2(256)   PATH '$.FullName',
        EMAIL           VARCHAR2(1000)  PATH '$.Email'
    )
) jt;
/