create table "Users"
(
    "Id"                   NUMBER(19) generated by default on null as identity
        constraint "PK_Users"
            primary key,
    "UserName"             NVARCHAR2(256),
    "NormalizedUserName"   NVARCHAR2(256),
    "Email"                NVARCHAR2(256),
    "NormalizedEmail"      NVARCHAR2(256),
    "EmailConfirmed"       BOOLEAN    not null,
    "PasswordHash"         NVARCHAR2(2000),
    "SecurityStamp"        NVARCHAR2(2000),
    "ConcurrencyStamp"     NVARCHAR2(2000),
    "PhoneNumber"          NVARCHAR2(2000),
    "PhoneNumberConfirmed" BOOLEAN    not null,
    "TwoFactorEnabled"     BOOLEAN    not null,
    "LockoutEnd"           TIMESTAMP(7) WITH TIME ZONE,
    "LockoutEnabled"       BOOLEAN    not null,
    "AccessFailedCount"    NUMBER(10) not null
)
/

create index "EmailIndex"
    on "Users" ("NormalizedEmail")
/

create unique index "UserNameIndex"
    on "Users" ("NormalizedUserName")
/
