CREATE TABLE "Users"
(
    "Id"                   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT "PK_Users" PRIMARY KEY,
    "UserName"             NVARCHAR2(256),
    "NormalizedUserName"   NVARCHAR2(256),
    "Email"                NVARCHAR2(256),
    "NormalizedEmail"      NVARCHAR2(256),
    "EmailConfirmed"       NUMBER(1) NOT NULL,
    "PasswordHash"         NVARCHAR2(2000),
    "SecurityStamp"        NVARCHAR2(2000),
    "ConcurrencyStamp"     NVARCHAR2(2000),
    "PhoneNumber"          NVARCHAR2(2000),
    "PhoneNumberConfirmed" NUMBER(1) NOT NULL,
    "TwoFactorEnabled"     NUMBER(1) NOT NULL,
    "LockoutEnd"           TIMESTAMP(7) WITH TIME ZONE,
    "LockoutEnabled"       NUMBER(1) NOT NULL,
    "AccessFailedCount"    NUMBER(10) NOT NULL,
);
/

create index "EmailIndex"
    on "Users" ("NormalizedEmail")
/

create unique index "UserNameIndex"
    on "Users" ("NormalizedUserName")
/

ALTER TABLE USERS
ADD BRANCH_ID NUMBER(19);
/
