-- USER
create table USERS
(
    ID               NUMBER(19) generated by default on null as identity primary key,
    USER_NAME              VARCHAR2(256 char)                     not null
        unique,
    NORMALIZED_USER_NAME   VARCHAR2(256 char)                     not null
        unique,
    EMAIL                  VARCHAR2(256 char)                     not null
        unique,
    NORMALIZED_EMAIL       VARCHAR2(256 char)                     not null
        unique,
    EMAIL_CONFIRMED        CHAR         default 'N',
    PASSWORD_HASH          VARCHAR2(256 char)                     not null,
    SECURITY_STAMP         VARCHAR2(256 char),
    CONCURRENCY_STAMP      VARCHAR2(256 char),
    PHONE_NUMBER           VARCHAR2(20 char),
    PHONE_NUMBER_CONFIRMED CHAR         default 'N',
    TWO_FACTOR_ENABLED     CHAR         default 'N',
    MFA_SECRET             VARCHAR2(100 char),
    LOCKOUT_END            TIMESTAMP(6),
    LOCKOUT_ENABLED        CHAR         default 'Y',
    ACCESS_FAILED_COUNT    NUMBER(10)   default 0,
    FULL_NAME              VARCHAR2(200 char),
    CREATED_AT             TIMESTAMP(6) default CURRENT_TIMESTAMP not null,
    LAST_LOGIN             TIMESTAMP(6),
    IS_ACTIVE              CHAR         default 'Y',
    BRANCH_ID              NUMBER(19)
)
/

-- ROLE_CLAIMS
create table ROLE_CLAIMS
(
    ID          NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    ROLE_ID     NUMBER(19)                             not null,
    CLAIM_TYPE  VARCHAR2(100 char)                     not null,
    CLAIM_VALUE VARCHAR2(100 char),
    DESCRIPTION VARCHAR2(1000 char)
)
/

create index IX_ROLE_CLAIMS_ROLE_ID
    on ROLE_CLAIMS (ROLE_ID)
/

create index IX_ROLE_CLAIMS_CLAIM_TYPE
    on ROLE_CLAIMS (CLAIM_TYPE)
/

-- USER_CLAIMS
CREATE TABLE USER_CLAIMS
(
    ID           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
        PRIMARY KEY,
    USER_ID      NUMBER(19) NOT NULL,
    CLAIM_TYPE   VARCHAR2(256 CHAR),
    CLAIM_VALUE  VARCHAR2(256 CHAR)
)
/

CREATE INDEX IX_USER_CLAIMS_USER_ID
    ON USER_CLAIMS (USER_ID)
/

-- USER_ROLES
CREATE TABLE USER_ROLES
(
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
)
/

CREATE INDEX IX_USER_ROLES_ROLE_ID
    ON USER_ROLES (ROLE_ID)
/

CREATE INDEX IX_USER_ROLES_USER_ID
    ON USER_ROLES (USER_ID)
/

-- ROLES
create table ROLE_REQUESTS
(
    ID             NUMBER(19)        default "ASPNETIDENTITY"."ISEQ$$_115630".nextval generated by default on null as identity
		primary key,
    ENTITY_ID      NUMBER(19),
    ACTION         VARCHAR2(20 char)                           not null,
    STATUS         VARCHAR2(10 char) default 'PENDING'         not null,
    REQUESTED_DATA CLOB                                        not null,
    COMMENTS       NVARCHAR2(500),
    MAKER_ID       VARCHAR2(256 char)                          not null,
    REQUESTED_DATE TIMESTAMP(6)      default CURRENT_TIMESTAMP not null,
    CHECKER_ID     VARCHAR2(256 char),
    APPROVE_DATE   TIMESTAMP(6)
)
/

create index SYS_C0032551
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_ENTITY_ID
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_STATUS
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_MAKER_ID
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_CHECKER_ID
    on ROLE_REQUESTS ()
/



-- USER_TOKENS