-- ROLES
create table ROLE_REQUESTS
(
    ID             NUMBER(19)        default "ASPNETIDENTITY"."ISEQ$$_115630".nextval generated by default on null as identity
		primary key,
    ENTITY_ID      NUMBER(19),
    ACTION         VARCHAR2(20 char)                           not null,
    STATUS         VARCHAR2(10 char) default 'PENDING'         not null,
    REQUESTED_DATA CLOB                                        not null,
    COMMENTS       NVARCHAR2(500),
    MAKER_ID       VARCHAR2(256 char)                          not null,
    REQUESTED_DATE TIMESTAMP(6)      default CURRENT_TIMESTAMP not null,
    CHECKER_ID     VARCHAR2(256 char),
    APPROVE_DATE   TIMESTAMP(6)
)
/

create index SYS_C0032551
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_ENTITY_ID
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_STATUS
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_MAKER_ID
    on ROLE_REQUESTS ()
/

create index IX_ROLE_REQUESTS_CHECKER_ID
    on ROLE_REQUESTS ()
/

create table ROLES
(
    ID                NUMBER(19)          default "ASPNETIDENTITY"."ISEQ$$_115606".nextval generated by default on null as identity
		primary key,
    NAME              VARCHAR2(256 char)                            not null
        unique,
    NORMALIZED_NAME   VARCHAR2(256 char)
        unique,
    CONCURRENCY_STAMP VARCHAR2(256 char),
    CODE              VARCHAR2(255 char)                            not null
        unique,
    DESCRIPTION       VARCHAR2(1000 char) default '',
    IS_ACTIVE         CHAR                default 'Y'
        check (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT        TIMESTAMP(6)        default CURRENT_TIMESTAMP not null,
    LAST_UPDATED      TIMESTAMP(6)
)
/

-- USER_TOKENS