create table "Roles"
(
    "Id"               NUMBER(19) generated by default on null as identity
        constraint "PK_Roles"
            primary key,
    "Name"             NVARCHAR2(256),
    "NormalizedName"   NVARCHAR2(256),
    "ConcurrencyStamp" NVARCHAR2(2000)
)
/

create unique index "RoleNameIndex"
    on "Roles" ("NormalizedName")
/

