-- SCRIPT: V2.2_enhance_roles_table.sql - Enhanced Role Management with Draft/Approval

-- ================================================
-- ENHANCE ROLES TABLE FOR DRAFT/APPROVAL MANAGEMENT
-- ================================================

-- Add STATUS column to track role state
ALTER TABLE ROLES ADD STATUS VARCHAR2(20) DEFAULT 'APPROVED' CHECK (STATUS IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED'));

-- Add VERSION column for versioning
ALTER TABLE ROLES ADD VERSION NUMBER(10) DEFAULT 1;

-- Add PARENT_ID for linking draft to original
ALTER TABLE ROLES ADD PARENT_ID NUMBER(19) REFERENCES ROLES(ID);

-- Add MAKER_ID and CHECKER_ID for audit trail
ALTER TABLE ROLES ADD MAKER_ID VARCHAR2(256 CHAR);
ALTER TABLE ROLES ADD CHECKER_ID VARCHAR2(256 CHAR);

-- Add REQUEST_ID to link with ROLE_REQUESTS
ALTER TABLE ROLES ADD REQUEST_ID NUMBER(19) REFERENCES ROLE_REQUESTS(ID);

-- Create indexes for better performance
CREATE INDEX IX_ROLES_STATUS ON ROLES(STATUS);
CREATE INDEX IX_ROLES_PARENT_ID ON ROLES(PARENT_ID);
CREATE INDEX IX_ROLES_MAKER_ID ON ROLES(MAKER_ID);
CREATE INDEX IX_ROLES_CHECKER_ID ON ROLES(CHECKER_ID);
CREATE INDEX IX_ROLES_REQUEST_ID ON ROLES(REQUEST_ID);

-- Update existing roles to have APPROVED status
UPDATE ROLES SET STATUS = 'APPROVED' WHERE STATUS IS NULL;
/ 