-- Migration: V3.1__create_table_branch_cache.sql
-- Description: Create BRANCH_CACHE table for caching Branch data from System service

CREATE TABLE BRANCH_CACHE (
    ID NUMBER(19) NOT NULL,
    CODE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    BRANCH_TYPE NUMBER(10) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    DESCRIPTION VARCHAR2(500),
    LAST_SYNCED_AT TIMESTAMP(6) NOT NULL,
    LAST_SYNCED_BY VARCHAR2(100),
    CREATED_DATE TIMESTAMP(6) NOT NULL,
    CREATED_BY VARCHAR2(100),
    UPDATED_DATE TIMESTAMP(6),
    UPDATED_BY VARCHAR2(100),
    CONSTRAINT PK_BRANCH_CACHE PRIMARY KEY (ID)
);

-- Create unique index on CODE
CREATE UNIQUE INDEX IDX_BRANCH_CACHE_CODE ON BRANCH_CACHE (CODE);

-- Create index on IS_ACTIVE
CREATE INDEX IDX_BRANCH_CACHE_ACTIVE ON BRANCH_CACHE (IS_ACTIVE);

-- Create sequence for ID
CREATE SEQUENCE SEQ_BRANCH_CACHE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger for auto-increment ID
CREATE OR REPLACE TRIGGER TRG_BRANCH_CACHE_ID
    BEFORE INSERT ON BRANCH_CACHE
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SEQ_BRANCH_CACHE_ID.NEXTVAL;
    END IF;
END;
/

-- Add comments
COMMENT ON TABLE BRANCH_CACHE IS 'Cache table for Branch data synchronized from System service';
COMMENT ON COLUMN BRANCH_CACHE.ID IS 'Primary key';
COMMENT ON COLUMN BRANCH_CACHE.CODE IS 'Branch code from System service';
COMMENT ON COLUMN BRANCH_CACHE.NAME IS 'Branch name from System service';
COMMENT ON COLUMN BRANCH_CACHE.BRANCH_TYPE IS 'Branch type from System service';
COMMENT ON COLUMN BRANCH_CACHE.IS_ACTIVE IS 'Active status (Y/N)';
COMMENT ON COLUMN BRANCH_CACHE.DESCRIPTION IS 'Branch description from System service';
COMMENT ON COLUMN BRANCH_CACHE.LAST_SYNCED_AT IS 'Last synchronization timestamp';
COMMENT ON COLUMN BRANCH_CACHE.LAST_SYNCED_BY IS 'User who performed last sync';
