create table "RoleClaims"
(
    "Id"         NUMBER(10) generated by default on null as identity
        constraint "PK_RoleClaims"
            primary key,
    "RoleId"     NUMBER(19) not null
        constraint "FK_RoleClaims_Roles_RoleId"
            references "Roles"
                on delete cascade,
    "ClaimType"  NVARCHAR2(2000),
    "ClaimValue" NVARCHAR2(2000)
)
/

create index "IX_RoleClaims_RoleId"
    on "RoleClaims" ("RoleId")
/
