create table "UserClaims"
(
    "Id"         NUMBER(10) generated by default on null as identity
        constraint "PK_UserClaims"
            primary key,
    "UserId"     NUMBER(19) not null
        constraint "FK_UserClaims_Users_UserId"
            references "Users"
                on delete cascade,
    "ClaimType"  NVARCHAR2(2000),
    "ClaimValue" NVARCHAR2(2000)
)
/

create index "IX_UserClaims_UserId"
    on "UserClaims" ("UserId")
/

