CREATE TABLE "Departments" (
    ID                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME               VARCHAR2(400),                     -- Tên phòng ban/chi nhánh
    ADDRESS            VARCHAR2(100),                     -- Tên người quản lý
    DESCRIPTION        CLOB,                              -- Mô tả
    STATUS             CHAR(1),                           -- Trạng thái (A: Active, E: Expired,...)
    CREATEDDATE       TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    LASTMODIFIEDDATE   TIMESTAMP(7) WITH TIME ZONE
);
/
