CREATE TABLE "Departments" (
    ID                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME               VARCHAR2(400),                     -- Tên phòng ban/chi nhánh
    ADDRESS            VARCHAR2(100),                     -- Tên người quản lý
    DESCRIPTION        CLOB,                              -- Mô tả
    STATUS             CHAR(1),                           -- Trạng thái (A: Active, E: Expired,...)
    CREATEDDATE        TIMESTAMP(7) WITH TIME ZONE NOT NULL,
    LASTMODIFIEDDATE   TIMESTAMP(7) WITH TIME ZONE
);
/

CREATE TABLE "DEPARTMENT_REQUESTS" (
    ID                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- ID tự tăng
    DEPARTMENT_ID      NUMBER(19), -- NULL nếu tạo mới
    NAME               VARCHAR2(400), -- Tên phòng ban/chi nhánh
    ADDRESS            VARCHAR2(100), -- Địa chỉ hoặc tên người quản lý
    DESCRIPTION        CLOB, -- Mô tả phòng ban
    ACTION_TYPE        VARCHAR2(10), -- CREATE / UPDATE / DELETE
    REQUEST_STATUS     VARCHAR2(20), -- PENDING / APPROVED / REJECTED / CANCELED
    APPROVED_BY        NUMBER(19), -- ID người duyệt
    APPROVED_AT        TIMESTAMP(7) WITH TIME ZONE, -- Thời gian duyệt
    NOTE               CLOB, -- Ghi chú duyệt/từ chối
    CREATEDDATE        TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Ngày tạo
    LASTMODIFIEDDATE   TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Ngày chỉnh sửa
);
/

ALTER TABLE "Departments"
ADD PROCESS_STATUS VARCHAR2(1000);
/

UPDATE "Departments"
SET PROCESS_STATUS = 'PA' WHERE 0 = 0;
/

ALTER TABLE "Departments"
MODIFY PROCESS_STATUS VARCHAR2(1000) NOT NULL;
/
