create table BRANCH_MASTER
(
    ID      NUMBER(19) generated by default on null as identity
        primary key,
    CODE    VARCHAR2(50 char) not null,
    NAME    NVARCHAR2(500)    not null,
    ADDRESS NVARCHAR2(500)
)
/

create table BRANCH_REQUEST_HEADER
(
    ID             NUMBER(19) generated by default on null as identity
		primary key,
    ACTION         VARCHAR2(20 char)  not null,
    STATUS         VARCHAR2(10 char)  not null,
    REQUESTED_BY   VARCHAR2(100 char) not null,
    APPROVE_BY     VARCHAR2(100 char),
    APPROVE_DATE   DATE,
    COMMENTS       NVARCHAR2(500),
    REQUESTED_DATE TIMESTAMP(6) default CURRENT_TIMESTAMP
)
/

create table BRANCH_REQUEST_DATA
(
    ID         NUMBER(19) generated by default on null as identity
        primary key,
    REQUEST_ID NUMBER(19)        not null,
    CODE       VARCHAR2(50 char) not null,
    NAME       NVARCHAR2(500)    not null,
    ADDRESS    NVARCHAR2(500),
    JSON_DATA  CLOB
)
/

create table BRANCH_AUDIT_LOG
(
    ID           NUMBER(19) generated by default on null as identity
        primary key,
    ENTITY_ID    NUMBER(19)         not null,
    OPERATION    VARCHAR2(20 char)  not null,
    OLD_VALUE    CLOB,
    NEW_VALUE    CLOB,
    REQUESTED_BY VARCHAR2(100 char) not null,
    APPROVE_BY   VARCHAR2(100 char),
    LOG_DATE     DATE               not null
)
/
