INSERT INTO "Investors" (NO, FULLNAME, EMAIL, PHONE, CREATEDDATE, LASTMODIFIEDDATE)
VALUES ('INV001', 'Nguyen Van A', 'nguyenvana@example.com', '0987654321', SYSTIMESTAMP, NULL);

INSERT INTO "Investors" (NO, FULLNAME, EMAIL, PHONE, CREATEDDATE, LASTMODIFIEDDATE)
VALUES ('INV002', 'Tran Thi B', 'tranthib@example.com', '0971122334', SYSTIMESTAMP, NULL);

INSERT INTO "Investors" (NO, FULLNAME, EMAIL, PHONE, CREATEDDATE, LASTMODIFIEDDATE)
VALUES ('INV003', 'Le Van C', NULL, '0969988776', SYSTIMESTAMP, NULL);

COMMIT;
/
