INSERT INTO "SubAccounts" (INVESTOR_ID, ACCOUNT_NO, ACCOUNT_TYPE, BALANCE, STATUS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (1, 'CASH-001', 'CASH', 1000000, 'ACTIVE', SYSTIMESTAMP, NULL);

INSERT INTO "SubAccounts" (INVESTOR_ID, ACCOUNT_NO, ACCOUNT_TYPE, BALANCE, STATUS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (1, 'MARGIN-001', 'MARGIN', 500000, 'ACTIVE', SYSTIMESTAMP, NULL);

INSERT INTO "SubAccounts" (INVESTOR_ID, ACCOUNT_NO, ACCOUNT_TYPE, BALANCE, STATUS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (2, 'CASH-002', 'CASH', 2000000, 'ACTIVE', SYSTIMESTAMP, NULL);

INSERT INTO "SubAccounts" (INVESTOR_ID, ACCOUNT_NO, ACCOUNT_TYPE, BALANCE, STATUS, CREATEDDATE, LASTMODIFIEDDATE)
VALUES (3, 'CASH-003', 'CASH', 1500000, 'ACTIVE', SYSTIMESTAMP, NULL);

COMMIT;
/
