INSERT INTO "Branches" (CODE, NAME, ADDRESS, REGION, MANAGER, ESTABLISHED_DATE, STATUS, CREATEDDATE, CREATEDBY)
VALUES ('BR001', N'Chi nhánh Hà Nội', N'123 Đường Trần Duy Hưng, Hà Nội', N'Miền Bắc', N'Nguyễn Văn A', TO_DATE('2010-05-20', 'YYYY-MM-DD'), 'ACTIVE', SYSTIMESTAMP, 'admin');

INSERT INTO "Branches" (CODE, NAME, ADDRESS, REGION, MANAGER, ESTABLISHED_DATE, STATUS, CREATEDDATE, CREATEDBY)
VALUES ('BR002', N'Chi nhánh TP.HCM', N'456 Đường Nguyễn Huệ, Quận 1', N'Miền Nam', N'Trần Thị B', TO_DATE('2012-09-10', 'YYYY-MM-DD'), 'ACTIVE', SYSTIMESTAMP, 'admin');

INSERT INTO "Branches" (CODE, NAME, ADDRESS, REGION, MANAGER, ESTABLISHED_DATE, STATUS, CREATEDDATE, CREATEDBY)
VALUES ('BR003', N'Chi nhánh Đà Nẵng', N'789 Đường Bạch Đằng, Đà Nẵng', N'Miền Trung', N'Lê Văn C', TO_DATE('2015-01-15', 'YYYY-MM-DD'), 'INACTIVE', SYSTIMESTAMP, 'admin');
/

INSERT INTO "BranchHistories" (BRANCH_ID, CHANGE_TYPE, OLD_DATA, NEW_DATA, COMMENTS, CREATEDDATE, CREATEDBY)
VALUES (1, 'UPDATE', '{"NAME":"Chi nhánh Hà Nội cũ"}', '{"NAME":"Chi nhánh Hà Nội"}', N'Cập nhật tên chi nhánh', SYSTIMESTAMP, 'admin');

INSERT INTO "BranchHistories" (BRANCH_ID, CHANGE_TYPE, OLD_DATA, NEW_DATA, COMMENTS, CREATEDDATE, CREATEDBY)
VALUES (2, 'UPDATE', '{"STATUS":"INACTIVE"}', '{"STATUS":"ACTIVE"}', N'Kích hoạt lại chi nhánh', SYSTIMESTAMP, 'admin');
/

INSERT INTO "BranchRequests" (BRANCH_ID, REQUEST_TYPE, PROPOSED_DATA, REASON, STATUS, REQUESTED_BY, CREATEDDATE, CREATEDBY)
VALUES (1, 'UPDATE', '{"MANAGER":"Nguyễn Văn B"}', N'Thay đổi người quản lý', 'PENDING', 'admin', SYSTIMESTAMP, 'admin');

INSERT INTO "BranchRequests" (BRANCH_ID, REQUEST_TYPE, PROPOSED_DATA, REASON, STATUS, REQUESTED_BY, CREATEDDATE, CREATEDBY)
VALUES (3, 'DELETE', '{"STATUS":"INACTIVE"}', N'Đóng cửa chi nhánh do hoạt động kém', 'APPROVED', 'supervisor', SYSTIMESTAMP, 'supervisor');
